const DUCK_NAMESPACE = 'SELECTED_SEASON';
const FETCH_NAMESPACE = `${DUCK_NAMESPACE}/FETCH`;
const PLAYER_FILTER = 'PLAYER_FILTER';
const PLAYER_FILTER_NAMESPACE = `${DUCK_NAMESPACE}/${PLAYER_FILTER}`;

export {
    DUCK_NAMESPACE,
    FETCH_NAMESPACE,
    PLAYER_FILTER,
    PLAYER_FILTER_NAMESPACE,
};
