const DUCK_NAMESPACE = 'LEAGUES';
const FETCH_NAMESPACE = `${DUCK_NAMESPACE}/FETCH`;
const ADD_NAMESPACE = `${DUCK_NAMESPACE}/ADD`;

export {
    DUCK_NAMESPACE,
    FETCH_NAMESPACE,
    ADD_NAMESPACE,
};
