const DUCK_NAMESPACE = 'PLAYERS';
const DATA_NAMESPACE = 'PLAYER_DATA';
const FETCH = `${DUCK_NAMESPACE}/FETCH`;
const FILTER = `${DUCK_NAMESPACE}/FILTER`;

export {
    DUCK_NAMESPACE,
    DATA_NAMESPACE,
    FETCH,
    FILTER
}