const DUCK_NAMESPACE = 'PLAYERS';
const FETCH = `FETCH`;
const FETCH_NAMESPACE = `${DUCK_NAMESPACE}/${FETCH}`;
const FILTER = `FILTER`;
const FILTER_NAMESPACE = `${DUCK_NAMESPACE}/${FILTER}`;

export {
    DUCK_NAMESPACE,
    FETCH,
    FETCH_NAMESPACE,
    FILTER,
    FILTER_NAMESPACE,
}