const DUCK_NAMESPACE = 'PLAYERS';
const DATA_NAMESPACE = 'PLAYER_DATA';
const FETCH_PLAYERS = `${DUCK_NAMESPACE}/FETCH_PLAYERS`;
const FETCH_PLAYERS_COMPLETED = `${DUCK_NAMESPACE}/FETCH_PLAYERS_COMPLETED`;
const FETCH_PLAYERS_FAILED = `${DUCK_NAMESPACE}/FETCH_PLAYERS_FAILED`;

export {
    DUCK_NAMESPACE,
    DATA_NAMESPACE,
    FETCH_PLAYERS,
    FETCH_PLAYERS_COMPLETED,
    FETCH_PLAYERS_FAILED,
}